# Configuración principal de build para Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Redirección para Single Page Applications (SPAs) como React
# Esto es CRUCIAL para que las rutas de react-router-dom funcionen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200